### ISSUE TITLE
Two tailed t-test

### ISSUE THREAD

**Issue by Zawan-uts** [BaderLab/Transfer-Learning-BNER-Bioinformatics-2018#5]
Hi,

Do you report standard deviations in your publication in order to do t-test?
How do you perform t-test when comparing with Habibi's paper, as they don't report standard deviation in their paper?

**Comment by JohnGiorgi** [comment]
Hi,

> Do you report standard deviations in your publication in order to do t-test?

The standard deviations are not reported but were used to conduct a two-tailed t-test. We simply used a Google Sheets formula to compute the p value based on our results over 5 runs.

> How do you perform t-test when comparing with Habibi's paper, as they don't report standard deviation in their paper?

We compute the p-value as per usual, here is an R code snippet

```R
#################################### T-TEST #################################### 
# change these
mu <- 78.22 # baseline score
x <- c(82.16, 82.72, 82.92, 79.72, 77.06)  # my score over 5 runs

# run t-test
N <- length(x)
x.bar <- sum(x) / N
sigma.sqrd <- var(x)

t.value <- (x.bar - mu) / (sd(x) / sqrt(N))
t.value
p.value <- 2*pt(-abs(t.value), 10e10)
p.value

print('RUNNING T-TEST...')
if (p.value <= 0.001) {
  print('significant to p <= 0.001 (**)')
} else if (p.value <= 0.05) {
  print('significant to p <= 0.05 (*)')
} else {
  print('not statistically significant')
}

mu; x.bar
```

where `x.bar` is the average of our results (over 5 runs) and is compared to `mu`, Habibi's results. 

Hopefully that makes sense, let me know otherwise!
